### ISSUE TITLE
Use the first image's load event instead of the window's event

### ISSUE THREAD

**Issue by eshiota** [larimaza/Karusel_my-photo-gallery-plugin#4]
If you get the image's width on the `window`'s `load` event here:

```javascript
window.addEventListener('load', function () {
```

the karusel will work only after all images of the page (both related and non-related to the karusel) are completely loaded. If you add the event listener to the karusel's first image instead, you'll get the width as soon as that image is loaded. This will allow the user to interact with the page faster.

**Comment by larimaza** [comment]
Fixed: 3c76f91
